apiVersion: v1
data:
  prometheus-additional.yaml: LSBqb2JfbmFtZTogImNzdnNlcnZlciIKICBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6IFsiY3N2c2VydmVyLXN2Yy5jc3ZzZXJ2ZXIuc3ZjLmNsdXN0ZXIubG9jYWwiXQoKIA==
kind: Secret
metadata:
  name: additional-scrape-configs