apiVersion: v1
kind: Service
metadata:
  name: alertmanager-svc
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: alertmanager-app
