apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prometheus

namespace: monitoring

bases:
  - prometheus-operator-crd

resources:
- namespace.yaml
- additional-scrape-configs.yaml  
- prometheus-app.yaml 
- prometheus-svc.yaml
- alertmanager-svc.yaml   
- prometheus-rules.yaml
- alertmanager-app.yaml
- alertmanager-config.yaml


