apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    prometheus: prometheus-app
  type: LoadBalancer
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090